name: Trigger auto deployment for mei-qs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mei-qs-AutoDeployTrigger-5e90ddb6-298a-4f8f-b203-e84990a93def.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEIQS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEIQS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEIQS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io/vmeilei62/hello-world:latest
          registryUsername: ${{ secrets.MEIQS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEIQS_REGISTRY_PASSWORD }}
          containerAppName: mei-qs
          resourceGroup: mei-env
          imageToBuild: docker.io/vmeilei62/hello-world:latest/mei-qs:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


